export { default as About } from './About/About'
export { default as Contact } from './Contact/Contact'
export { default as Education } from './Education/Education'
export { default as Section } from './Section/Section'
export * from './Skills/Skills'
export { default as Slider } from './Slider/Slider'
export { default as Works } from './Works/Works'
